# Generated by Django 5.0.14 on 2026-04-16 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("steam_id", models.BigIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("date_release", models.DateField()),
                ("last_crawled_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("developer", models.JSONField()),
                ("publisher", models.JSONField()),
                ("description", models.TextField()),
                ("total_reviews", models.IntegerField(default=0)),
                ("review_rating", models.IntegerField(default=0)),
                ("url_steam", models.URLField()),
                ("url_image", models.URLField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
