# Generated by Django 5.0.14 on 2026-04-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("playlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Games",
            new_name="Game",
        ),
    ]
