# Generated by Django 5.0.14 on 2026-04-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="url_steam",
        ),
    ]
