# Generated by Django 5.0.14 on 2026-04-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_game_url_steam"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="url_steam",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="url_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
