# Generated by Django 5.0.14 on 2026-04-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_tag_game_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="tags",
        ),
    ]
