# Generated by Django 5.0.14 on 2026-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_alter_playlist_iduser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="idUser",
            new_name="user",
        ),
    ]
