# Generated by Django 5.0.14 on 2026-04-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=1)),
                ('is_staff', models.BooleanField(default=0)),
            ],
        ),
    ]
